version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=dmpn
      - POSTGRES_USER=dmpn
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:80"
    depends_on:
      - db
